Class {
	#name : 'PresizerSample',
	#superclass : 'Object',
	#instVars : [
		'callsite',
		'collectionInstance'
	],
	#category : 'Presize-Objects',
	#package : 'Presize',
	#tag : 'Objects'
}

{ #category : 'accessing' }
PresizerSample >> callsite [

	^ callsite
]

{ #category : 'accessing' }
PresizerSample >> callsite: anObject [

	callsite := anObject
]

{ #category : 'accessing' }
PresizerSample >> collectionInstance [

	^ collectionInstance
]

{ #category : 'accessing' }
PresizerSample >> collectionInstance: anObject [

	collectionInstance := anObject
]
